app/basic_strategy/__init__.py
from flask import Blueprint

bp = Blueprint('basic_strategy', __name__)

from . import routes  # noqa: W0611

app/basic_strategy/routes.py
import gzip
from flask import abort, request, Response, json
from flask_login import login_required, current_user
from . import bp
from .. import db
from ..routes import my_render_template
from ..models import BasicStrategyPlayStats


@bp.route('/')
def index():
    return my_render_template(
        'basic_strategy/index.html', title='Basic Strategy')


@bp.route('/play-stats/latest')
@login_required
def play_stats_latest():
    BSPS = BasicStrategyPlayStats
    DEFAULT_PLAYSTATS = \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0," + \
        "0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0"
    DEFAULT_STREAK = 0
    if not current_user.is_authenticated:
        # should never happen, right?
        abort(403)
    row = BSPS.query.filter_by(
        user_id=current_user.id).order_by(
            BSPS.timestamp.desc()).first()
    data_bytes = json.dumps({
        'play_stats': DEFAULT_PLAYSTATS if not row else row.play_stats,
        'streak': DEFAULT_STREAK if not row else row.streak,
    }).encode('utf-8')
    if 'gzip' in request.accept_encodings:
        resp = Response(gzip.compress(data_bytes))
        resp.headers['Content-Encoding'] = 'gzip'
    else:
        resp = Response(data_bytes)
    resp.headers['Content-Type'] = 'application/json'
    return resp


def play_stats_seem_valid(s):
    # "999/999," 360 times
    MAX_LEN = 360 * 8
    if len(s) > MAX_LEN:
        return False
    # must have 360 items
    parts = s.split(',')
    if len(parts) != 360:
        return False
    for part in parts:
        # each must look like a fraction
        sub_parts = part.split('/')
        if len(sub_parts) != 2:
            return False
        try:
            # with valid ints
            n, d = [int(_) for _ in sub_parts]
        except ValueError:
            return False
        # and numerator can't be bigger than denominator
        if n > d:
            return False
    return True


@bp.route('/play-stats', methods=['POST'])
@login_required
def play_stats():
    BSPS = BasicStrategyPlayStats
    if not current_user.is_authenticated:
        # should never happen, right?
        abort(403)
    if not play_stats_seem_valid(request.json['play_stats']):
        abort(400)
    row = BSPS(
        user_id=current_user.id,
        play_stats=request.json['play_stats'],
        streak=request.json['streak'],
    )
    db.session.add(row)
    db.session.commit()
    return ('', 204)

app/templates/basic_strategy/index.html
{% extends "base.html" %}
{% block extra_css %}
<link href=/static/basic-strategy.css rel=stylesheet>
{% endblock %}
{% block content %}
{% set wasm_bin, wasm_js = wasm_urls('basic_strategy') %}
<!-- Note the usage of `type=module` here as this is an ES6 module -->
<script type="module">
    // Use ES module import syntax to import functionality from the module
    // that we have compiled.
    //
    // Note that the `default` import is an initialization function which
    // will "boot" the module and make it ready to use. Currently browsers
    // don't support natively imported WebAssembly as an ES module, but
    // eventually the manual initialization won't be required!
    import init, {
        on_button_hit,
        on_button_stand,
        on_button_double,
        on_button_split,
        on_button_surrender,
        on_button_clear_stats,
        rust_init,
        play_stats_from_state,
        streak_from_state,
        statistics_into_state,
        should_upload_statistics,
        reset_next_upload_statistics,
    } from '{{ wasm_js }}';

    {% if current_user.is_authenticated %}
    window.upload_statistics = function() {
        let data = {
            'play_stats': play_stats_from_state(),
            'streak': streak_from_state(),
        };
        let req = new XMLHttpRequest();
        req.addEventListener("error", function(e) {
            flash_statistics_message("Error uploading stats");
        });
        req.addEventListener("abort", function(e) {
            flash_statistics_message("Aborted upload of stats");
        });
        req.addEventListener("load", function(e) {
            if (req.status >= 200 && req.status < 300) {
                flash_statistics_message("Uploaded latest statistics :)");
            } else {
                flash_statistics_message("Problem uploading latest statistics");
                console.log(req);
            }
        });
        req.open("POST", "{{ url_for('basic_strategy.play_stats') }}", true);
        req.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        req.send(JSON.stringify(data));
    }

    function download_statistics() {
        flash_statistics_message("Downloading latest statistics ...");
        let req = new XMLHttpRequest();
        req.addEventListener("error", function(e) {
            flash_statistics_message("Error fetching latest statistics");
            console.log(req);
        });
        req.addEventListener("abort", function(e) {
            flash_statistics_message("Aborted fetching latest statistics");
            console.log(req);
        });
        req.addEventListener("load", function(e) {
            let play_stats = req.response['play_stats'];
            let streak = req.response['streak'];
            statistics_into_state(play_stats, streak);
            flash_statistics_message("Downloaded latest statistics");
        });
        req.open("GET", "{{ url_for('basic_strategy.play_stats_latest') }}", true);
        req.responseType = "json";
        req.send();
    }
    {% endif %}
    {% if current_user.is_authenticated %}
    let flash_statistics_message_fade_interval = 0;
    let flash_statistics_message_update_every_ms = 50;
    let flash_statistics_message_duration_ms = 3000;
    window.flash_statistics_message = function(msg) {
        let elm = document.getElementById("upload_message");
        elm.textContent = msg;
        // clean up from existing fading, if any
        window.clearInterval(flash_statistics_message_fade_interval);
        flash_statistics_message_fade_interval = 0;
        // start new fading
        let opacity = 1; // initial
        elm.style.opacity = opacity;
        flash_statistics_message_fade_interval = window.setInterval(() => {
            opacity -= flash_statistics_message_update_every_ms / flash_statistics_message_duration_ms;
            elm.style.opacity = opacity;
            if (opacity <= 0) {
                window.clearInterval(flash_statistics_message_fade_interval);
                flash_statistics_message_fade_interval = 0;
            }
        }, flash_statistics_message_update_every_ms);
    };
    {% endif %}

    let flash_hint_message_fade_interval = 0;
    let flash_hint_message_update_every_ms = 100;
    let flash_hint_message_duration_ms = 10000;
    window.flash_hint_message = function(msg) {
        let elm = document.getElementById("hint");
        elm.textContent = msg;
        // clean up from existing fading, if any
        window.clearInterval(flash_hint_message_fade_interval);
        flash_hint_message_fade_interval = 0;
        // start new fading
        let opacity = 1; // initial
        elm.style.opacity = opacity;
        flash_hint_message_fade_interval = window.setInterval(() => {
            opacity -= flash_hint_message_update_every_ms / flash_hint_message_duration_ms;
            elm.style.opacity = opacity;
            if (opacity <= 0) {
                window.clearInterval(flash_hint_message_fade_interval);
                flash_hint_message_fade_interval = 0;
            }
        }, flash_hint_message_update_every_ms);
    };

    {% if current_user.is_authenticated %}
    let inactivity_upload_timeout = 0;
    let inactivity_timeout_duration_ms = 2000;
    {% endif %}
    window.on_button = function(button_name) {
        if (button_name == "hit") {
            on_button_hit();
        } else if (button_name == "stand") {
            on_button_stand();
        } else if (button_name == "double") {
            on_button_double();
        } else if (button_name == "split") {
            on_button_split();
        } else if (button_name == "surrender") {
            on_button_surrender();
        } else if (button_name == "clear_stats") {
            on_button_clear_stats();
        } else {
            console.log("Unknown button name", button_name);
            return;
        }
        {% if current_user.is_authenticated %}
        if (inactivity_upload_timeout) {
            window.clearTimeout(inactivity_upload_timeout);
            inactivity_upload_timeout = 0;
        }
        if (should_upload_statistics()) {
            upload_statistics();
            reset_next_upload_statistics();
            flash_statistics_message("Uploading latest statistics ...");
        } else {
            inactivity_upload_timeout = window.setTimeout(() => {
                upload_statistics();
                reset_next_upload_statistics();
                flash_statistics_message("Uploading latest statistics ...");
            }, inactivity_timeout_duration_ms);
        }
        {% endif %}
    };

    async function run() {
    // First up we need to actually load the wasm file, so we use the
    // default export to inform it where the wasm file is located on the
    // server, and then we wait on the returned promise to wait for the
    // wasm to be loaded.
    // It may look like this: `await init('./pkg/without_a_bundler_bg.wasm');`,
    // but there is also a handy default inside `init` function, which uses
    // `import.meta` to locate the wasm file relatively to js file
    //
    // Note that instead of a string here you can also pass in an instance
    // of `WebAssembly.Module` which allows you to compile your own module.
    // Also note that the promise, when resolved, yields the wasm module's
    // exports which is the same as importing the `*_bg` module in other
    // modes
    await init();

    {# first argument: type of random, where 0 is draw random cards and 1 is
    choose a random cell weighted by user's Table<PlayStats> #}
    {% if current_user.is_anonymous %}
    rust_init(0);
    {% else %}
    rust_init(1);
    download_statistics();
    {% endif %}
    //let s = playstats_as_db_str();
    //console.log(s);
    //var req = new XMLHttpRequest();
    //req.open("POST", "{{ url_for('basic_strategy.play_stats') }}");
    //req.setRequestHeader("Content-Type", "text/plain");
    //req.send(s);
    //playstats_db_str_into_storage(s);
    }

    run();
    document.addEventListener("keydown", key => {
    if (key.key == "h" || key.key == "H") {
        on_button("hit");
    } else if (key.key == "s" || key.key == "S") {
        on_button("stand");
    } else if (key.key == "d" || key.key == "D") {
        on_button("double");
    } else if (key.key == "p" || key.key == "P") {
        on_button("split");
    } else if (key.key == "r" || key.key == "R") {
        on_button("surrender");
    }
    });
</script>
Player:<br/>
<span class=card id=player_cards></span><br/>
Dealer:<br/>
<span class=card id=dealer_cards></span><br/>
<span id=hint></span><br/>
<div id=buttons>
<a id=button_hit onClick='on_button("hit"); return false;'/><b>Hit</b></a>
<a id=button_stand onClick='on_button("stand"); return false;'/><b>Stand</b></a>
<a id=button_double onClick='on_button("double"); return false;'/><b>Double</b></a>
<a id=button_split onClick='on_button("split"); return false;'/><b>sPlit</b></a>
<a id=button_surrender onClick='on_button("surrender"); return false;'/><b>Surrender</b></a>
</div> <!-- buttons -->
<div id=stats>
Correct: <span id=num_correct>0</span>/<span id=num_seen>0</span><br/>
This hand: <span id=hand_num_correct>0</span>/<span id=hand_num_seen>0</span><br/>
Streak: <span id=num_streak>0</span>
{% if current_user.is_authenticated %}
<span id=upload_message></span><br/>
{% else %}
<br/>
{% endif %}
<a onClick='on_button("clear_stats"); return false;' /><i>Clear stats</i></a>
</div>
<div id=strat>
<a onClick='document.getElementById("strat_html").classList.toggle("hide"); return false;' /><i>Show/hide strategy card</i></a>
<br/>
<div id=strat_html></div> <!-- strat_html -->
</div> <!-- strat -->
{% endblock %}