app/time_trial/__init__.py
from flask import Blueprint

bp = Blueprint('time_trial', __name__)

from . import routes  # noqa: W0611

app/time_trial/routes.py
from flask import abort, request
from flask_login import login_required, current_user
from ..routes import my_render_template
from ..models import TimeTrialResult
from .. import db
from . import bp


@bp.route('/')
@login_required
def index():
    return my_render_template('time_trial/index.html', title='Time Trial')


def results_seem_valid(results):
    ''' VERY weak check as this is cbor and I don't want to have to try to
    parse just to send it to the DB '''
    if not len(results):
        return False
    if type(results) != bytes:
        return False
    return True


def try_parse_results(results_dict):
    ''' They come from the user as a dict with key=position and value=byte.
    Just concatenate the bytes together, or return None if we can't
    '''
    # dicts are ordered in python now? Let's make sure that stays the case
    last = -1
    results_bytes = b''
    for k, v in results_dict.items():
        try:
            k = int(k)
        except ValueError:
            return None
        if v < 0 or v > 255:
            return None
        assert k == last + 1
        last += 1
        results_bytes += bytes([v])
    return results_bytes


@bp.route('/results', methods=['POST'])
@login_required
def results():
    if not current_user.is_authenticated:
        # should never happen, right?
        abort(403)
    results = try_parse_results(request.json['results'])
    if not results or not results_seem_valid(results):
        abort(400)
    row = TimeTrialResult(
        user_id=current_user.id,
        hands=results,
    )
    db.session.add(row)
    db.session.commit()
    return ('', 204)

app/templates/time_trial/index.html
{% extends "base.html" %}
{% block extra_css %}
<link href=/static/time-trial.css rel=stylesheet>
{% endblock %}
{% block content %}
{% set wasm_bin, wasm_js = wasm_urls('time_trial') %}
{% set num_hands = 30 %}
<!-- Note the usage of `type=module` here as this is an ES6 module -->
<script type="module">
    // Use ES module import syntax to import functionality from the module
    // that we have compiled.
    //
    // Note that the `default` import is an initialization function which
    // will "boot" the module and make it ready to use. Currently browsers
    // don't support natively imported WebAssembly as an ES module, but
    // eventually the manual initialization won't be required!
    import init, {
        on_button_hit,
        on_button_stand,
        on_button_double,
        on_button_split,
        on_button_surrender,
        okay_to_upload_results,
        results_from_state,
        clear_results,
        rust_init,
    } from '{{ wasm_js }}';

    async function run() {
        await init();
        rust_init({{ num_hands }});
    }
    run();

    window.on_button = function(button_name) {
        if (button_name == "hit") {
            on_button_hit();
        } else if (button_name == "stand") {
            on_button_stand();
        } else if (button_name == "double") {
            on_button_double();
        } else if (button_name == "split") {
            on_button_split();
        } else if (button_name == "surrender") {
            on_button_surrender();
        } else if (button_name == "upload") {
            upload_results();
        } else {
            console.log("Unknown button name", button_name);
            return;
        }
    };

    window.upload_results = function(results) {
        if (!okay_to_upload_results()) {
            return;
        }
        let data = {
            'results': results_from_state(),
        };
        let req = new XMLHttpRequest();
        req.addEventListener("error", function(e) {
            flash_hint_message("Error uploading results");
        });
        req.addEventListener("abort", function(e) {
            flash_hint_message("Aborted upload of results");
        });
        req.addEventListener("load", function(e) {
            if (req.status >= 200 && req.status < 300) {
                flash_hint_message("Uploaded results :)");
                clear_results();
            } else {
                flash_hint_message("Problem uploading results");
                console.log(req);
            }
        });
        req.open("POST", "{{ url_for('time_trial.results') }}", true);
        req.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        req.send(JSON.stringify(data));
    }

    let flash_hint_message_fade_interval = 0;
    let flash_hint_message_update_every_ms = 100;
    let flash_hint_message_duration_ms = 10000;
    window.flash_hint_message = function(msg) {
        set_hint_message(msg);
        let elm = document.getElementById("hint");
        // start new fading
        let opacity = 1; // initial
        elm.style.opacity = opacity;
        flash_hint_message_fade_interval = window.setInterval(() => {
            opacity -= flash_hint_message_update_every_ms / flash_hint_message_duration_ms;
            elm.style.opacity = opacity;
            if (opacity <= 0) {
                window.clearInterval(flash_hint_message_fade_interval);
                flash_hint_message_fade_interval = 0;
            }
        }, flash_hint_message_update_every_ms);
    };
    window.set_hint_message = function(msg) {
        let elm = document.getElementById("hint");
        elm.textContent = msg;
        // clean up from existing fading, if any
        window.clearInterval(flash_hint_message_fade_interval);
        flash_hint_message_fade_interval = 0;
    }

    document.addEventListener("keydown", key => {
        if (key.key == "h" || key.key == "H") {
            on_button("hit");
        } else if (key.key == "s" || key.key == "S") {
            on_button("stand");
        } else if (key.key == "d" || key.key == "D") {
            on_button("double");
        } else if (key.key == "p" || key.key == "P") {
            on_button("split");
        } else if (key.key == "r" || key.key == "R") {
            on_button("surrender");
        }
    });
</script>
Player:<br/>
<span class=card id=player_cards></span><br/>
Dealer:<br/>
<span class=card id=dealer_cards></span><br/>
<span id=hint>
    See how quickly you can work through {{ num_hands }} hands! Time starts the
    moment you respond to this first hand.
</span><br/>
<div id=buttons>
<a id=button_hit onClick='on_button("hit"); return false;'/><b>Hit</b></a>
<a id=button_stand onClick='on_button("stand"); return false;'/><b>Stand</b></a>
<a id=button_double onClick='on_button("double"); return false;'/><b>Double</b></a>
<a id=button_split onClick='on_button("split"); return false;'/><b>sPlit</b></a>
<a id=button_surrender onClick='on_button("surrender"); return false;'/><b>Surrender</b></a>
<a id=button_upload_yes class=hide onClick='on_button("upload"); return false;'><b>Yes</b></a>
<a id=button_upload_no class=hide href=''><b>No</b></a>
</div> <!-- buttons -->
<div id=strat>
<a onClick='document.getElementById("strat_html").classList.toggle("hide"); return false;' /><i>Show/hide strategy card</i></a>
<br/>
<div id=strat_html></div> <!-- strat_html -->
</div> <!-- strat -->
{% endblock %}