app/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)

from . import routes  # noqa: W0611

app/profile/routes.py
from flask import redirect, url_for, current_app, abort
from flask_login import login_required, current_user
from . import bp
from ..models import User
from ..routes import my_render_template


@bp.route('/', methods=['GET'])
@login_required
def index():
    if not current_user.is_authenticated:
        # should never happen, right?
        return redirect(url_for('misc_routes.index'))
    return redirect(
        url_for('profile.show',
                id_hash=current_app.hashids.encode(current_user.id)))


@bp.route('/<id_hash>')
def show(id_hash):
    # this returns a tuple
    int_id = current_app.hashids.decode(id_hash)
    # 0 len if invalid hashid, >1 if hashid for a 2+ len tuple
    if len(int_id) != 1:
        abort(404)
    int_id = int_id[0]
    user = User.query.filter_by(id=int_id).first()
    # might have been a valid hashid for a user that doesn't exist
    if not user:
        abort(404)
    return my_render_template(
        'profile/index.html', title=f'{user.username}', user=user)

app/templates/base.html
<html>
    <head>
      {% if title %}
      <title>{{ title }} - Blackjack</title>
      {% else %}
      <title>Blackjack</title>
      {% endif %}
      <meta name=viewport content="width=device-width, initial-scale=1">
      <link href=/static/mvp.css rel=stylesheet>
      <link href=/static/global.css rel=stylesheet>
      {% block extra_css %} {% endblock %}
    </head>
    <body>
    <header>
      <nav>
        <a href='{{ url_for('misc_routes.index') }}'><img alt="BJ logo" id=logo src="/static/logo.png" /></a>
        <ul>
            <li><a href="{{ url_for('misc_routes.index') }}">Home</a></li>
            <li>Train<ul>
                    <li><a href="{{ url_for('basic_strategy.index') }}">Basic Strategy</a></li>
                    <li><a href="{{ url_for('time_trial.index') }}">Time Trial</a></li>
                    <li><a href="{{ url_for('counting.index') }}">Counting</a></li>
                    <li><a href="{{ url_for('deviations.index') }}">Deviations</a></li>
            </ul></li>
	    <li><a href="{{ url_for('misc_routes.faq') }}">FAQ</a></li>
            {% if current_user.is_anonymous %}
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            {% else %}
            <li><a href="{{ url_for('profile.index') }}">Profile</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% endif %}
        </ul>
      </nav>
    </header>
    <main>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </main>
    <footer></footer>
    {% if analytics %}
    <noscript><img src="https://a.pastly.xyz/ingress/62ffc1f5-1d60-4532-87ad-e0124abcaff4/pixel.gif"></noscript> <script src="https://a.pastly.xyz/ingress/62ffc1f5-1d60-4532-87ad-e0124abcaff4/script.js"></script>
    {% endif %}
    </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block extra_css %}
{% endblock %}
{% block content %}
<article>
    <h1>Free Blackjack Basic Strategy Training</h1>
    <p>Welcome to the home of the best blackjack training programs. Here you
    can learn how to <b>reduce the house edge</b> and <b>maximize your chances
    of beating the casino</b>.</p>
    <aside>
        <p>Work on your basic strategy with the <b>most common</b> set of
        Blackjack rules that you will find at <b>real casinos</b>!</p>
        <a href="{{ url_for('basic_strategy.index') }}"><i>Train for free</i></a>
    </aside>
    <h1>No signup required</h1>
    <p>Train for free, right in your browser! On your laptop or on your phone.
    At home or on the go. <b>Our software works in any modern browser</b>.</p>
    <p>Supported Browsers and Platforms</p>
    <img style="height: 50px;" src=/static/logos/chrome.svg alt=chrome />
    <img style="height: 50px;" src=/static/logos/firefox.svg alt=firefox />
    <img style="height: 50px;" src=/static/logos/safari_64x64.png alt=safari />
    <img style="height: 50px;" src=/static/logos/windows.svg alt=windows />
    <img style="height: 50px;" src=/static/logos/Android_robot.svg alt=android />
    <img style="height: 50px;" src=/static/logos/apple.svg alt=ios />
    <br/>
    <aside>
        <h1>Features</h1>
        <ul>
            <li>Works offline.</li>
            <li>Optimized for touch, keyboard, or mouse input. <b>Play how you want</b></li>
            <li>No downloads. No bloated app to download. Play right here, for free, anywhere.</li>
            <li>Optional reference <b>basic strategy card</b> so you don't have to leave the page.</li>
            <li>Statistics including <b>streak</b> and <b>number of correct responses</b> for every possible hand.</li>
        </ul>
        <a href="{{ url_for('basic_strategy.index') }}"><i>Try it now</i></a>
    </aside>
    <h1>Get even more out of your game</h1>
    <p>Create an account and we'll track your performance across sessions. Log
    in on all your devices and track your statistics wherever you go.</p>
    <p><a href="{{ url_for('auth.login') }}">Login</a> or <a href="{{ url_for('auth.register') }}">sign up</a> today.</p>
</article>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
            <span class=error>[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span class=error>[{{ error }}]</span>
            {% endfor %}
        </p>
        <!--
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        -->
        <p>{{ form.submit() }}</p>
    <p> New User? <a href="{{ url_for('register') }}">Register</a></p>
    </form>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1>{{ user.username }}</h1>
<img src="{{ robohash_url(user.id, size=150) }}" alt="{{ user.username }} profile picture"/>
{% endblock %}

app/templates/train-basic-strategy.html
{% extends "base.html" %}
{% block extra_css %}
<link href=/static/basic-strategy.css rel=stylesheet>
{% endblock %}
{% block content %}
{% set wasm_bin, wasm_js = wasm_urls('basic_strategy') %}
<!-- Note the usage of `type=module` here as this is an ES6 module -->
<script type="module">
    // Use ES module import syntax to import functionality from the module
    // that we have compiled.
    //
    // Note that the `default` import is an initialization function which
    // will "boot" the module and make it ready to use. Currently browsers
    // don't support natively imported WebAssembly as an ES module, but
    // eventually the manual initialization won't be required!
    import init, {
        on_button_hit,
        on_button_stand,
        on_button_double,
        on_button_split,
        on_button_surrender,
        on_button_clear_stats,
        rust_init,
        playstats_as_db_str,
        playstats_db_str_into_storage,
    } from '{{ wasm_js }}';

    {% if current_user.is_authenticated %}
    window.upload_playstats = function() {
        let s = playstats_as_db_str();
        let req = new XMLHttpRequest();
        req.open("POST", "{{ url_for('train_basic_strategy_play_stats') }}", true);
        req.setRequestHeader("Content-Type", "text/plain");
        req.send(s);
    }

    function download_playstats() {
        let req = new XMLHttpRequest();
        req.addEventListener("error", function(e) {
            console.log("Request to fetch latest play stats had error:", e);
        });
        req.addEventListener("abort", function(e) {
            console.log("Request to fetch latest play stats aborted:", e);
        });
        req.addEventListener("load", function(e) {
            console.log("Request completed:", e);
            console.log("Data:", req.responseText);
        });
        req.open("GET", "{{ url_for('train_basic_strategy_play_stats_latest') }}", true);
        req.send();
    }
    {% endif %}

    async function run() {
    // First up we need to actually load the wasm file, so we use the
    // default export to inform it where the wasm file is located on the
    // server, and then we wait on the returned promise to wait for the
    // wasm to be loaded.
    // It may look like this: `await init('./pkg/without_a_bundler_bg.wasm');`,
    // but there is also a handy default inside `init` function, which uses
    // `import.meta` to locate the wasm file relatively to js file
    //
    // Note that instead of a string here you can also pass in an instance
    // of `WebAssembly.Module` which allows you to compile your own module.
    // Also note that the promise, when resolved, yields the wasm module's
    // exports which is the same as importing the `*_bg` module in other
    // modes
    await init();

    {# first argument: type of random, where 0 is draw random cards and 1 is
    choose a random cell weighted by user's Table<PlayStats> #}
    {% if current_user.is_anonymous %}
    rust_init(0);
    {% else %}
    rust_init(1);
    download_playstats();
    {% endif %}
    //let s = playstats_as_db_str();
    //console.log(s);
    //var req = new XMLHttpRequest();
    //req.open("POST", "{{ url_for('train_basic_strategy_play_stats') }}");
    //req.setRequestHeader("Content-Type", "text/plain");
    //req.send(s);
    //playstats_db_str_into_storage(s);
    }

    run();
    window.on_button_hit = on_button_hit;
    window.on_button_stand = on_button_stand;
    window.on_button_double = on_button_double;
    window.on_button_split = on_button_split;
    window.on_button_surrender = on_button_surrender;
    window.on_button_clear_stats = on_button_clear_stats;
    document.addEventListener("keydown", key => {
    if (key.key == "h" || key.key == "H") {
        on_button_hit();  
    } else if (key.key == "s" || key.key == "S") {
        on_button_stand();  
    } else if (key.key == "d" || key.key == "D") {
        on_button_double();  
    } else if (key.key == "p" || key.key == "P") {
        on_button_split();  
    } else if (key.key == "r" || key.key == "R") {
        on_button_surrender();
    }
    });
</script>
Player:<br/>
<span class=card id=player_cards></span><br/>
Dealer:<br/>
<span class=card id=dealer_cards></span><br/>
<div id=buttons>
<a id=button_hit onClick='on_button_hit(); return false;'/><b>Hit</b></a>
<a id=button_stand onClick='on_button_stand(); return false;'/><b>Stand</b></a>
<a id=button_double onClick='on_button_double(); return false;'/><b>Double</b></a>
<a id=button_split onClick='on_button_split(); return false;'/><b>sPlit</b></a>
<a id=button_surrender onClick='on_button_surrender(); return false;'/><b>Surrender</b></a>
</div> <!-- buttons -->
<div id=stats>
Correct: <span id=num_correct>0</span>/<span id=num_seen>0</span><br/>
This hand: <span id=hand_num_correct>0</span>/<span id=hand_num_seen>0</span><br/>
Streak: <span id=num_streak>0</span><br/>
<!--
<a id=button_fetch_stats><i>Fetch stats</i></a>
-->
{% if current_user.is_authenticated %}
<a id=button_upload_stats onClick='upload_playstats(); return false'><i>Upload stats</i></a>
{% endif %}
<a onClick='on_button_clear_stats(); return false;' /><i>Clear stats</i></a>
</div>
<div id=hint>
</div> <!-- hint -->
<div id=strat>
<a onClick='document.getElementById("strat_html").classList.toggle("hide"); return false;' /><i>Show/hide strategy card</i></a>
<br/>
<div id=strat_html></div> <!-- strat_html -->
</div> <!-- strat -->
{% endblock %}

app/templates/train-free-play.html
{% extends "base.html" %}
{% block extra_css %}
<link href=/static/free-play.css rel=stylesheet>
{% endblock %}
{% block content %}
{% set wasm_bin, wasm_js = wasm_urls('free_play') %}
<!-- Note the usage of `type=module` here as this is an ES6 module -->
<script type="module">
    // Use ES module import syntax to import functionality from the module
    // that we have compiled.
    //
    // Note that the `default` import is an initialization function which
    // will "boot" the module and make it ready to use. Currently browsers
    // don't support natively imported WebAssembly as an ES module, but
    // eventually the manual initialization won't be required!
    import init, {
        on_button_hit,
        on_button_stand,
        on_button_double,
        on_button_split,
        on_button_surrender,
        on_button_clear_stats,
    } from '{{ wasm_js }}';

    async function run() {
    // First up we need to actually load the wasm file, so we use the
    // default export to inform it where the wasm file is located on the
    // server, and then we wait on the returned promise to wait for the
    // wasm to be loaded.
    // It may look like this: `await init('./pkg/without_a_bundler_bg.wasm');`,
    // but there is also a handy default inside `init` function, which uses
    // `import.meta` to locate the wasm file relatively to js file
    //
    // Note that instead of a string here you can also pass in an instance
    // of `WebAssembly.Module` which allows you to compile your own module.
    // Also note that the promise, when resolved, yields the wasm module's
    // exports which is the same as importing the `*_bg` module in other
    // modes
    await init();

    //// And afterwards we can use all the functionality defined in wasm.
    //const result = add(1, 2);
    //console.log(`1 + 2 = ${result}`);
    //if (result !== 3)
    //  throw new Error("wasm addition doesn't work!");
    //init_panic_hook();
    }

    run();
    window.on_button_hit = on_button_hit;
    window.on_button_stand = on_button_stand;
    window.on_button_double = on_button_double;
    window.on_button_split = on_button_split;
    window.on_button_surrender = on_button_surrender;
    window.on_button_clear_stats = on_button_clear_stats;
    document.addEventListener("keydown", key => {
    if (key.key == "h" || key.key == "H") {
        on_button_hit();  
    } else if (key.key == "s" || key.key == "S") {
        on_button_stand();  
    } else if (key.key == "d" || key.key == "D") {
        on_button_double();  
    } else if (key.key == "p" || key.key == "P") {
        on_button_split();  
    } else if (key.key == "r" || key.key == "R") {
        on_button_surrender();
    }
    });
</script>
Player:<br/>
<span class=card id=player_cards></span><br/>
Dealer:<br/>
<span class=card id=dealer_cards></span><br/>
<div id=buttons>
<a id=button_hit onClick='on_button_hit(); return false;'/><b>Hit</b></a>
<a id=button_stand onClick='on_button_stand(); return false;'/><b>Stand</b></a>
<a id=button_double onClick='on_button_double(); return false;'/><b>Double</b></a>
<a id=button_split onClick='on_button_split(); return false;'/><b>sPlit</b></a>
<a id=button_surrender onClick='on_button_surrender(); return false;'/><b>Surrender</b></a>
</div> <!-- buttons -->
<div id=stats>
Correct: <span id=num_correct>0</span>/<span id=num_seen>0</span><br/>
This hand: <span id=hand_num_correct>0</span>/<span id=hand_num_seen>0</span><br/>
Streak: <span id=num_streak>0</span><br/>
<a onClick='on_button_clear_stats(); return false;' /><i>Clear stats</i></a>
</div>
<div id=hint>
</div> <!-- hint -->
<div id=strat>
<a onClick='document.getElementById("strat_html").classList.toggle("hide"); return false;' /><i>Show/hide strategy card</i></a>
<br/>
<div id=strat_html></div> <!-- strat_html -->
</div> <!-- strat -->
{% endblock %}